# Generated by Django 4.1.3 on 2022-11-05 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=120, verbose_name='Firm Name')),
                ('region', models.CharField(max_length=120, verbose_name='Region')),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=120, verbose_name='Speciality')),
            ],
        ),
        migrations.CreateModel(
            name='Attorneys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender')),
                ('rate', models.CharField(max_length=10, verbose_name='Rate')),
                ('years', models.CharField(max_length=10, verbose_name='Years of practice')),
                ('state', models.CharField(max_length=120, verbose_name='State')),
                ('country', models.CharField(max_length=120, verbose_name='Country located')),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legally.firms')),
                ('speciality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legally.speciality')),
            ],
        ),
    ]
